num_clients:
  # - 8 
  # - 16
  # - 32
  # - 128
  # - 64

# Many Clients
  # - 100
  # - 1000
  # - 3000
  # - 5000
  - 10000

dims:
  # - 1e1
  - 1e2
  # - 1e3
  # - 1e4
  # - 1e5
  # - 1e6
  #- 1e7
  
num_trials: 5
midnight: 2022-06-02
protocol_name:  Large_Malicious_Acorn
protocol_location_client: agent.AcornNew.AcornClientAgent
protocol_location_server: agent.AcornNew.AcornServiceAgent
default_computation_delay: 5
params:
  s_len: 710
  malicious: true
  dropout_fraction: 0.05
  num_rounds: 5
  client_bandwidth: 10000000     # in megabits per second
  server_bandwidth: 10000000 # 1 #100
