num_clients:
  # - 8
  # - 16
  # - 32
  # - 128
  # - 64 

  # Many Clients
  - 100
  - 1000
  - 3000
  - 5000
  - 10000
dims:
  # - 1e1
  - 1e2
  # - 1e3
  # - 1e4
  # - 1e5
  # - 1e6
  # - 1e7 
num_trials: 5
midnight: 2022-06-02
protocol_name: Large_Baseline
protocol_location_client: agent.Baseline.BaselineClientAgent
protocol_location_server: agent.Baseline.BaselineServiceAgent
default_computation_delay: 5
params:
  s_len: 10
  k: 3
  malicious: false #true
  dropout_fraction: 0.05
  num_rounds: 2
  client_bandwidth: 10000000     # in megabits per second
  server_bandwidth: 10000000 
