num_clients:
  - 8
  - 16
  - 32
  - 128 
  - 64 
dims:
  - 1e1
  - 1e2
  - 1e3
  - 1e4
  - 1e5
  - 1e6
  - 1e7 
num_trials: 5
midnight: 2022-06-02
protocol_name: Low_Latency_Bell_final
protocol_location_client: agent.Bell.BellClientAgent
protocol_location_server: agent.Bell.BellServiceAgent
default_computation_delay: 5
params:
  k_node_connectivity: 9
