num_clients:
  - 64 
  # - 8 
  # - 16
  # - 32
  # - 128

dims:
  # - 1e1
  - 1e2
  # - 1e3
  # - 1e4
  # - 1e5
  # - 1e6
  # - 1e7
num_trials: 5
midnight: 2022-06-02
protocol_name: Low_Client_Bandwidth_Malicious_Shamir # Low_Server_Bandwidth_Shamir
protocol_location_client: agent.Shamir.ShamirClientAgent
protocol_location_server: agent.Shamir.ShamirServiceAgent
default_computation_delay: 5
params:
  dropout_fraction: 0.05
  num_rounds: 4
  malicious: true 
  client_bandwidth: 1 #10000000     # in megabits per second
  server_bandwidth: 10000000 

  