num_clients:
  - 64 
  - 8 
  - 16
  - 32
  - 128
dims:
  - 1e1
  - 1e2
  - 1e3
  - 1e4
  - 1e5
  - 1e6
  - 1e7
num_trials: 1
midnight: 2022-06-02
protocol_name: Shamir
protocol_location_client: agent.Shamir.ShamirClientAgent
protocol_location_server: agent.Shamir.ShamirServiceAgent
default_computation_delay: 5
params:
  