num_clients:
  # - 8
  # - 16
  # - 32
  # - 128 
  # - 64

  # # Many Clients
  # - 108
  - 1020
  # - 3002
  # - 5016
  # - 10000 

  # Other Clients
  # - 136
  # - 1208
  # - 3136
  # - 5040
  # - 10350 
dims:
  # - 1e1
  # - 1e2 
  - 1e3  
  # - 1e4
  # - 1e5
  # - 1e6
  # - 1e7
num_trials: 5
midnight: 2022-06-02
protocol_name: Round_Sharing_Sharing #Sharing_Sharing  #Mid_Bandwidth_Sharing_Sharing #Malicious_Sharing_Sharing #
protocol_location_client: agent.SharingSharing.SharingSharingClientAgent
protocol_location_server: agent.SharingSharing.SharingSharingServiceAgent
default_computation_delay: 5
params:
  group_size: 34 #40 #8 #15 #450 #34 #38 
  share_number: 2
  s_len: 710
  k: 1
  dropout_fraction: 0.05
  num_rounds: 4
  malicious: false
  client_bandwidth: 10000000     # in megabits per second
  server_bandwidth: 10000000 #100 1 #

# General Experiments (0.5, 0.5)
# Latency Experiments
# Bandwidth Experiments
# Dropout rate varies
# Malicious client rate varies

# 5% 5% setting
# 100 12
# 1000 34 
# 3000 38
# 5000 38
# 10000 40

# High_Bandwidth => High_Server_Bandwidth_Sharing_Sharing => Default Settings 
# Low_Bandwidth  => Low_Server_Bandwidth_Sharing_Sharing
# Mid_Bandwidth  =>
# Low_Bandwidth_Client
